[31m[1mERROR   [0m unit test:logger.py:83 this is test!