{"name": "test_add_user_already_exists", "status": "passed", "steps": [{"name": "add user {'user_name': 'adim333', 'user_password': 'YQpV5EOV'}", "status": "passed", "start": 1679691556786, "stop": 1679691556806}, {"name": "getting the user adim333", "status": "passed", "start": 1679691556806, "stop": 1679691556822}, {"name": "add user {'user_name': 'adim333', 'user_password': 'YQpV5EOV'}", "status": "passed", "start": 1679691556822, "stop": 1679691556840}], "attachments": [{"name": "log", "source": "bc83d347-025b-4809-aaa2-34a6c7803f4d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "cfd04d5a-59e9-4f4e-9d1e-9fde474bd198-attachment.txt", "type": "text/plain"}], "start": 1679691556786, "stop": 1679691556840, "uuid": "e46bb5eb-bac7-4894-9685-e59454ea74a3", "historyId": "d1547a7b0f7584a5cc7d5fc11e478d70", "testCaseId": "2653eaebae43387b15ebaa804ec6db84", "fullName": "tests.test_users.TestUsers#test_add_user_already_exists", "labels": [{"name": "epic", "value": "users api"}, {"name": "story", "value": "a client cant add exists usernames"}, {"name": "severity", "value": 1}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-9JHRV77"}, {"name": "thread", "value": "8036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}